services:
  jenkins:
    image: myjenkins-blueocean:2.462.2-1
    restart: on-failure
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    external: true

volumes:
  jenkins-data:
  jenkins-docker-certs:
