pipeline {
    agent any

    tools {
        golang 'Go 1.23'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/tomunix2000/revaluer-api.git'
            }
        }

        stage('Build') {
            steps {
                sh 'go build -o main'
            }
        }

        stage('Test') {
            steps {
                sh 'go test ./...'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t revaluer-api .'
            }
        }
    }
}