pipeline {
    agent {
        docker {
          image 'golang:1.22-alpine'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/tomunix2000/revaluer-api.git'
            }
        }

        stage('Build') {
            steps {
                sh 'go build -o main'
            }
        }

        stage('Test') {
            steps {
                sh 'go test ./...'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t revaluer-api .'
            }
        }
    }
}